# Generated by Django 3.0.6 on 2020-09-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='N',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
